---
output: html_document
---
## About Me {.tabset}

### Academic Experience 

__CDC Modeling Infectious Diseases (MInD) Project __     
    
+ Managed and cleaned over 10,000 pieces of structured and unstructured population-level data     
+ Performed statistical analyses, including multivariable logistic regression, survival analysis and longitudinal analysis to model potential factors of antimicrobial resistance infection among SARS-CoV-2 patients using SAS   
     
__US CHEESEHEAD’19 National Project__      

+ Measured foliar biochemical, physiological, morphological traits, including properties of LMA, sugars, starches, phenolics, nitrogen, carbon, d15N, d13C, phosphorus, potassium, etc.    
+ Modeled spectrums to analyze sub-mesoscale responses and spatial heterogeneity     
+ Refined numerical weather and climate prediction formulations of sub-grid processes        
     
### Working Experience

__United Nations__    
_Data Analysis Intern_     

+ Built secondary datasets from various sources and performed data management, quality checks and cleaning process  
+ Utilized R Markdown and Power BI to build data visualization and conduct descriptive analyses for tracking UN system-wide COVID-19 Vaccination Programme progress    
+ Complied weekly country specific analysis reports to United Nations Secretariat     
    
__Alzheimer’s Therapeutic Research Institute__      
_Biostatistics Intern_     

+ Developed automation frameworks for monthly analysis of data quality control using R    
+ Performed statistical analyses, such as linear and logistic regression analyses and ANOVA analysis, on clinical trial data to estimate efficacy and safety of Phase 2 and Phase 3 studies     
+ Created statistical/QC reports and detailed specifications for analysis files and consistency checks using R Markdown    

